# Generated by Django 6.1 on 2026-08-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Caracteristica',
                'verbose_name_plural': 'Caracteristicas',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('duracion', models.DurationField(verbose_name='Duracion')),
                ('sinopsis', models.CharField(max_length=300, verbose_name='Sinopsis')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.genero')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
        migrations.CreateModel(
            name='DetallePelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destacada', models.BooleanField(default=False, verbose_name='Destacada')),
                ('fecha_estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('clasificacion', models.CharField(blank=True, choices=[('TP', 'Todas las edades'), ('7', 'Mayores de 7 años'), ('12', 'Mayores de 12 años'), ('16', 'Mayores de 16 años'), ('18', 'Mayores de 18 años')], max_length=3, null=True, verbose_name='Clasificación por edad')),
                ('en_cartelera', models.BooleanField(default=False, verbose_name='En cartelera')),
                ('pelicula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='peliculas.peliculas')),
            ],
            options={
                'verbose_name': 'Detalle de pelicula',
                'verbose_name_plural': 'Detalles de peliculas',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, verbose_name='Identificador')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('tiempo_max', models.IntegerField(verbose_name='Tiempo Máximo')),
                ('caracteristicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='peliculas.caracteristicas')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
