# Generated by Django 6.1 on 2026-08-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/posters/', verbose_name='Póster'),
        ),
        migrations.DeleteModel(
            name='Caracteristicas',
        ),
        migrations.DeleteModel(
            name='Salas',
        ),
    ]
