# Generated by Django 5.2.17 on 2026-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_remove_salas_caracteristicas_peliculas_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='recaudacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se actualiza automáticamente con las ventas de entradas', max_digits=10, verbose_name='Recaudación'),
        ),
    ]
