# Generated by Django 5.2.17 on 2026-08-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_peliculas_recaudacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Nota media sobre 10. La importa importar_tmdb desde TMDB', max_digits=3, verbose_name='Puntuación'),
        ),
    ]
