# Generated by Django 5.2.17 on 2026-08-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_peliculas_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartelPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.BinaryField(verbose_name='Imagen')),
                ('tipo', models.CharField(default='image/jpeg', max_length=50, verbose_name='Tipo')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('pelicula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartel', to='peliculas.peliculas')),
            ],
            options={
                'verbose_name': 'Cartel',
                'verbose_name_plural': 'Carteles',
                'db_table': 'cartel_pelicula',
            },
        ),
    ]
