# Generated by Django 6.1 on 2026-08-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0002_remove_salas_caracteristicas_peliculas_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Característica de Sala',
                'verbose_name_plural': 'Características de Sala',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, verbose_name='Identificador')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('tiempo_max', models.IntegerField(verbose_name='Tiempo Máximo')),
                ('caracteristicas', models.ManyToManyField(related_name='salas', to='cartelera.caracteristicassala')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='PeliculasEnSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(verbose_name='Horario de Sesión')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas_en_sala', to='peliculas.peliculas')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas_en_sala', to='cartelera.sala')),
            ],
            options={
                'verbose_name': 'Película en Sala (Sesión)',
                'verbose_name_plural': 'Películas en Sala (Sesiones)',
            },
        ),
    ]
