# Generated by Django 6.1 on 2026-08-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
        ('peliculas', '0002_remove_salas_caracteristicas_peliculas_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='peliculasensala',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='peliculasensala',
            name='sala',
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(blank=True, choices=[('IMAX', 'IMAX'), ('2D', '2D'), ('3D', '3D'), ('LASER', 'Láser'), ('4DX', '4DX'), ('VIP', 'VIP')], null=True, verbose_name='Tipo de sala'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(verbose_name='Horario de Sesión')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='peliculas.peliculas', verbose_name='Película')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='cartelera.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['horario'],
            },
        ),
        migrations.DeleteModel(
            name='CaracteristicasSala',
        ),
        migrations.DeleteModel(
            name='PeliculasEnSala',
        ),
    ]
