# Generated by Django 5.2.17 on 2026-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0002_remove_sala_caracteristicas_and_more'),
        ('peliculas', '0002_remove_salas_caracteristicas_peliculas_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='horario',
            field=models.DateTimeField(help_text='Hora de apertura de sala (15 min antes de película)', verbose_name='Horario de Sesión'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('sala', 'horario'), name='unica_sesion_por_sala_hora'),
        ),
    ]
