# Generated by Django 5.2.17 on 2026-08-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0003_alter_sesion_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='precio_entrada',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Precio base de entrada para esta sala', max_digits=6, verbose_name='Precio entrada'),
        ),
    ]
