# Generated by Django 5.2.17 on 2026-08-24 22:07

import math

from django.db import migrations, models


def rejilla_desde_capacidad(apps, schema_editor):
    """Reparte la capacidad ya existente de cada sala en una rejilla coherente:
    ~14 butacas por fila, y tantas filas como hagan falta."""
    Sala = apps.get_model('cartelera', 'Sala')
    for sala in Sala.objects.all():
        capacidad = sala.capacidad or 150
        columnas = min(20, max(8, round(math.sqrt(capacidad * 1.8))))
        sala.columnas = columnas
        sala.filas = max(1, math.ceil(capacidad / columnas))
        sala.save(update_fields=['filas', 'columnas'])


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0004_sala_precio_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='columnas',
            field=models.PositiveIntegerField(default=15, verbose_name='Butacas por fila'),
        ),
        migrations.AddField(
            model_name='sala',
            name='filas',
            field=models.PositiveIntegerField(default=10, help_text='Filas del mapa de butacas', verbose_name='Filas'),
        ),
        migrations.RunPython(rejilla_desde_capacidad, migrations.RunPython.noop),
    ]
