# Generated by Django 5.2.17 on 2026-08-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartelera', '0003_alter_sesion_horario_and_more'),
        ('peliculas', '0002_remove_salas_caracteristicas_peliculas_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='peliculas.peliculas')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='cartelera.sala')),
            ],
            options={
                'verbose_name': 'Venta de entrada',
                'verbose_name_plural': 'Ventas de entradas',
                'db_table': 'venta_entrada',
            },
        ),
    ]
