# Generated by Django 5.2.17 on 2026-08-24 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0004_sala_precio_entrada'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaentrada',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='ventaentrada',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='ventaentrada',
            name='sala',
        ),
        migrations.AddField(
            model_name='ventaentrada',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de entradas'),
        ),
        migrations.AddField(
            model_name='ventaentrada',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='Precio unitario'),
        ),
        migrations.AddField(
            model_name='ventaentrada',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_vendidas', to='cartelera.sesion', verbose_name='Sesión'),
        ),
        migrations.AddField(
            model_name='ventaentrada',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
