# Generated by Django 5.2.17 on 2026-08-24 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0005_sala_columnas_sala_filas'),
        ('reservas', '0002_remove_ventaentrada_pelicula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaButaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField(verbose_name='Fila')),
                ('numero', models.PositiveIntegerField(verbose_name='Butaca')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='butacas_vendidas', to='cartelera.sesion', verbose_name='Sesión')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butacas', to='reservas.ventaentrada')),
            ],
            options={
                'verbose_name': 'Butaca vendida',
                'verbose_name_plural': 'Butacas vendidas',
                'db_table': 'entrada_butaca',
                'ordering': ['fila', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('sesion', 'fila', 'numero'), name='butaca_unica_por_sesion')],
            },
        ),
        migrations.CreateModel(
            name='ReservaButaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField(verbose_name='Fila')),
                ('numero', models.PositiveIntegerField(verbose_name='Butaca')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Comprador')),
                ('expira_en', models.DateTimeField(verbose_name='Expira')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butacas_reservadas', to='cartelera.sesion', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Butaca reservada',
                'verbose_name_plural': 'Butacas reservadas',
                'db_table': 'reserva_butaca',
                'ordering': ['fila', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('sesion', 'fila', 'numero'), name='reserva_unica_por_sesion')],
            },
        ),
    ]
